spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/hairok

  application:
    name: Hairok
